#!/usr/bin/env python3

import os
import subprocess
import time
import sys


def main() :
    # list all files in 2022/R and 2022/python
    rs = os.listdir(os.path.join("2022", "R"))
    rs = [os.path.join("2022", "R", i) for i in rs]
    rs.sort()
    
    py = os.listdir(os.path.join("2022", "python"))
    py = [os.path.join("2022", "python", i) for i in py]
    py.sort()
    
    scripts = []
    [scripts.append(i) for i in rs]
    [scripts.append(i) for i in py]
    n = max([len(s) for s in scripts])

    for script in scripts :
        print(script.ljust(n, " "), end=" ... ")
        sys.stdout.flush()
        tic = time.perf_counter()
        subprocess.run(script)
        toc = time.perf_counter()
        print(f"{toc - tic:0.2f}s".rjust(6, " "))

    return None


if __name__ == "__main__" :
    main()
